# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param result: The result of this InlineResponse200.  # noqa: E501
        :type result: str
        """
        self.swagger_types = {
            'result': str
        }

        self.attribute_map = {
            'result': 'result'
        }
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> str:
        """Gets the result of this InlineResponse200.

        Generated text from the language model.  # noqa: E501

        :return: The result of this InlineResponse200.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this InlineResponse200.

        Generated text from the language model.  # noqa: E501

        :param result: The result of this InlineResponse200.
        :type result: str
        """

        self._result = result
