# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1generate_parameters import V1generateParameters  # noqa: F401,E501
from swagger_server import util


class V1GenerateBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, model_id: str=None, inputs: List[str]=None, parameters: V1generateParameters=None):  # noqa: E501
        """V1GenerateBody - a model defined in Swagger

        :param model_id: The model_id of this V1GenerateBody.  # noqa: E501
        :type model_id: str
        :param inputs: The inputs of this V1GenerateBody.  # noqa: E501
        :type inputs: List[str]
        :param parameters: The parameters of this V1GenerateBody.  # noqa: E501
        :type parameters: V1generateParameters
        """
        self.swagger_types = {
            'model_id': str,
            'inputs': List[str],
            'parameters': V1generateParameters
        }

        self.attribute_map = {
            'model_id': 'model_id',
            'inputs': 'inputs',
            'parameters': 'parameters'
        }
        self._model_id = model_id
        self._inputs = inputs
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'V1GenerateBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1_generate_body of this V1GenerateBody.  # noqa: E501
        :rtype: V1GenerateBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_id(self) -> str:
        """Gets the model_id of this V1GenerateBody.

        ID of the language model.  # noqa: E501

        :return: The model_id of this V1GenerateBody.
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id: str):
        """Sets the model_id of this V1GenerateBody.

        ID of the language model.  # noqa: E501

        :param model_id: The model_id of this V1GenerateBody.
        :type model_id: str
        """

        self._model_id = model_id

    @property
    def inputs(self) -> List[str]:
        """Gets the inputs of this V1GenerateBody.

        Input text(s) for the language model.  # noqa: E501

        :return: The inputs of this V1GenerateBody.
        :rtype: List[str]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs: List[str]):
        """Sets the inputs of this V1GenerateBody.

        Input text(s) for the language model.  # noqa: E501

        :param inputs: The inputs of this V1GenerateBody.
        :type inputs: List[str]
        """

        self._inputs = inputs

    @property
    def parameters(self) -> V1generateParameters:
        """Gets the parameters of this V1GenerateBody.


        :return: The parameters of this V1GenerateBody.
        :rtype: V1generateParameters
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: V1generateParameters):
        """Sets the parameters of this V1GenerateBody.


        :param parameters: The parameters of this V1GenerateBody.
        :type parameters: V1generateParameters
        """

        self._parameters = parameters
