# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V1generateParametersModerationsHap(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: bool=None, threshold: float=None, output: bool=None):  # noqa: E501
        """V1generateParametersModerationsHap - a model defined in Swagger

        :param input: The input of this V1generateParametersModerationsHap.  # noqa: E501
        :type input: bool
        :param threshold: The threshold of this V1generateParametersModerationsHap.  # noqa: E501
        :type threshold: float
        :param output: The output of this V1generateParametersModerationsHap.  # noqa: E501
        :type output: bool
        """
        self.swagger_types = {
            'input': bool,
            'threshold': float,
            'output': bool
        }

        self.attribute_map = {
            'input': 'input',
            'threshold': 'threshold',
            'output': 'output'
        }
        self._input = input
        self._threshold = threshold
        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'V1generateParametersModerationsHap':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1generate_parameters_moderations_hap of this V1generateParametersModerationsHap.  # noqa: E501
        :rtype: V1generateParametersModerationsHap
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> bool:
        """Gets the input of this V1generateParametersModerationsHap.

        Whether to moderate the input.  # noqa: E501

        :return: The input of this V1generateParametersModerationsHap.
        :rtype: bool
        """
        return self._input

    @input.setter
    def input(self, input: bool):
        """Sets the input of this V1generateParametersModerationsHap.

        Whether to moderate the input.  # noqa: E501

        :param input: The input of this V1generateParametersModerationsHap.
        :type input: bool
        """

        self._input = input

    @property
    def threshold(self) -> float:
        """Gets the threshold of this V1generateParametersModerationsHap.

        Moderation threshold.  # noqa: E501

        :return: The threshold of this V1generateParametersModerationsHap.
        :rtype: float
        """
        return self._threshold

    @threshold.setter
    def threshold(self, threshold: float):
        """Sets the threshold of this V1generateParametersModerationsHap.

        Moderation threshold.  # noqa: E501

        :param threshold: The threshold of this V1generateParametersModerationsHap.
        :type threshold: float
        """

        self._threshold = threshold

    @property
    def output(self) -> bool:
        """Gets the output of this V1generateParametersModerationsHap.

        Whether to moderate the output.  # noqa: E501

        :return: The output of this V1generateParametersModerationsHap.
        :rtype: bool
        """
        return self._output

    @output.setter
    def output(self, output: bool):
        """Sets the output of this V1generateParametersModerationsHap.

        Whether to moderate the output.  # noqa: E501

        :param output: The output of this V1generateParametersModerationsHap.
        :type output: bool
        """

        self._output = output
