# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1generate_parameters_moderations import V1generateParametersModerations  # noqa: F401,E501
from swagger_server import util


class V1generateParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, decoding_method: str=None, repetition_penalty: float=None, min_new_tokens: int=None, max_new_tokens: int=None, moderations: V1generateParametersModerations=None):  # noqa: E501
        """V1generateParameters - a model defined in Swagger

        :param decoding_method: The decoding_method of this V1generateParameters.  # noqa: E501
        :type decoding_method: str
        :param repetition_penalty: The repetition_penalty of this V1generateParameters.  # noqa: E501
        :type repetition_penalty: float
        :param min_new_tokens: The min_new_tokens of this V1generateParameters.  # noqa: E501
        :type min_new_tokens: int
        :param max_new_tokens: The max_new_tokens of this V1generateParameters.  # noqa: E501
        :type max_new_tokens: int
        :param moderations: The moderations of this V1generateParameters.  # noqa: E501
        :type moderations: V1generateParametersModerations
        """
        self.swagger_types = {
            'decoding_method': str,
            'repetition_penalty': float,
            'min_new_tokens': int,
            'max_new_tokens': int,
            'moderations': V1generateParametersModerations
        }

        self.attribute_map = {
            'decoding_method': 'decoding_method',
            'repetition_penalty': 'repetition_penalty',
            'min_new_tokens': 'min_new_tokens',
            'max_new_tokens': 'max_new_tokens',
            'moderations': 'moderations'
        }
        self._decoding_method = decoding_method
        self._repetition_penalty = repetition_penalty
        self._min_new_tokens = min_new_tokens
        self._max_new_tokens = max_new_tokens
        self._moderations = moderations

    @classmethod
    def from_dict(cls, dikt) -> 'V1generateParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1generate_parameters of this V1generateParameters.  # noqa: E501
        :rtype: V1generateParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def decoding_method(self) -> str:
        """Gets the decoding_method of this V1generateParameters.

        Decoding method (e.g., \"greedy\").  # noqa: E501

        :return: The decoding_method of this V1generateParameters.
        :rtype: str
        """
        return self._decoding_method

    @decoding_method.setter
    def decoding_method(self, decoding_method: str):
        """Sets the decoding_method of this V1generateParameters.

        Decoding method (e.g., \"greedy\").  # noqa: E501

        :param decoding_method: The decoding_method of this V1generateParameters.
        :type decoding_method: str
        """

        self._decoding_method = decoding_method

    @property
    def repetition_penalty(self) -> float:
        """Gets the repetition_penalty of this V1generateParameters.

        Repetition penalty.  # noqa: E501

        :return: The repetition_penalty of this V1generateParameters.
        :rtype: float
        """
        return self._repetition_penalty

    @repetition_penalty.setter
    def repetition_penalty(self, repetition_penalty: float):
        """Sets the repetition_penalty of this V1generateParameters.

        Repetition penalty.  # noqa: E501

        :param repetition_penalty: The repetition_penalty of this V1generateParameters.
        :type repetition_penalty: float
        """

        self._repetition_penalty = repetition_penalty

    @property
    def min_new_tokens(self) -> int:
        """Gets the min_new_tokens of this V1generateParameters.

        Minimum number of new tokens.  # noqa: E501

        :return: The min_new_tokens of this V1generateParameters.
        :rtype: int
        """
        return self._min_new_tokens

    @min_new_tokens.setter
    def min_new_tokens(self, min_new_tokens: int):
        """Sets the min_new_tokens of this V1generateParameters.

        Minimum number of new tokens.  # noqa: E501

        :param min_new_tokens: The min_new_tokens of this V1generateParameters.
        :type min_new_tokens: int
        """

        self._min_new_tokens = min_new_tokens

    @property
    def max_new_tokens(self) -> int:
        """Gets the max_new_tokens of this V1generateParameters.

        Maximum number of new tokens.  # noqa: E501

        :return: The max_new_tokens of this V1generateParameters.
        :rtype: int
        """
        return self._max_new_tokens

    @max_new_tokens.setter
    def max_new_tokens(self, max_new_tokens: int):
        """Sets the max_new_tokens of this V1generateParameters.

        Maximum number of new tokens.  # noqa: E501

        :param max_new_tokens: The max_new_tokens of this V1generateParameters.
        :type max_new_tokens: int
        """

        self._max_new_tokens = max_new_tokens

    @property
    def moderations(self) -> V1generateParametersModerations:
        """Gets the moderations of this V1generateParameters.


        :return: The moderations of this V1generateParameters.
        :rtype: V1generateParametersModerations
        """
        return self._moderations

    @moderations.setter
    def moderations(self, moderations: V1generateParametersModerations):
        """Sets the moderations of this V1generateParameters.


        :param moderations: The moderations of this V1generateParameters.
        :type moderations: V1generateParametersModerations
        """

        self._moderations = moderations
