# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1generate_parameters_moderations_hap import V1generateParametersModerationsHap  # noqa: F401,E501
from swagger_server import util


class V1generateParametersModerations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hap: V1generateParametersModerationsHap=None):  # noqa: E501
        """V1generateParametersModerations - a model defined in Swagger

        :param hap: The hap of this V1generateParametersModerations.  # noqa: E501
        :type hap: V1generateParametersModerationsHap
        """
        self.swagger_types = {
            'hap': V1generateParametersModerationsHap
        }

        self.attribute_map = {
            'hap': 'hap'
        }
        self._hap = hap

    @classmethod
    def from_dict(cls, dikt) -> 'V1generateParametersModerations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1generate_parameters_moderations of this V1generateParametersModerations.  # noqa: E501
        :rtype: V1generateParametersModerations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hap(self) -> V1generateParametersModerationsHap:
        """Gets the hap of this V1generateParametersModerations.


        :return: The hap of this V1generateParametersModerations.
        :rtype: V1generateParametersModerationsHap
        """
        return self._hap

    @hap.setter
    def hap(self, hap: V1generateParametersModerationsHap):
        """Sets the hap of this V1generateParametersModerations.


        :param hap: The hap of this V1generateParametersModerations.
        :type hap: V1generateParametersModerationsHap
        """

        self._hap = hap
