listen 5173 default_server;
listen [::]:5173 default_server;

location /nginx_status {
    stub_status;
}

location / {
    # resolver 127.0.0.11;
    add_header Cache-Control "private, no-store, no-cache";
    #try_files $uri $uri/ /index.html =404;
    try_files $uri /index.html;
}

error_page   500 502 503 504  /50x.html;
location = /50x.html {
    root   /usr/share/nginx/html;
}