FROM registry.access.redhat.com/ubi9/python-311:latest

ADD --chown=1001:0 requirements.txt requirements.txt

RUN pip install -r requirements.txt

ADD --chown=1001:0 . .

EXPOSE 8080

CMD ["uvicorn", "main:app", \
    "--host=0.0.0.0", \
    "--port=8080"]